### ISSUE TITLE
Allow the user to change/update their email?

### ISSUE THREAD

**Issue by duarme** [mikker/passwordless#106]
Hello there and congrats on this gem! :)
I'm trying it out, migrating from devise, and so I'm trying to replicate the most important functionalities.

The one the puzzles me is **reconfirmable**, the one about a user that needs to update their email address. Devise stores the new one in a dedicated attribute `User#unconfirmed_email` then sends a confirmation email to the previous email. Only upon confirmation, the `unconfirmed_email` becomes the `email`.

How would you go about reproducing this feature the passwordless way?

I'm thinking about adding an `unconfirmed_email` attribute to `PasswordlessSession` instead and then sending a confirmation email with a magic link that points (redirects?) to a `PasswordlessSessionsController#update` action.

Does that sound right? 🤔  
How would you do it better please?

**Comment by rickychilcott** [comment]
This general approach could work.

Do you think in addition to authing from their old email, should they also auth from their new email once?
