### ISSUE TITLE
Support I18n

### ISSUE THREAD

**Issue by mftaff** [mikker/passwordless#11]
Hey man, 
I have been reading up on how to add I18n support to a gem, and mostly things seem pretty straightforward. 
The main issue I have come up with is how to provide an easy way for someone using the gem to customize the YAML files -  similar to how devise loads `devise.en.yml` into the main app's `config/locales` directory.

It seems like this happens in the gem's engine, but I haven't been able to find an example or documentation on how to do that. I have a feeling it is quite simple 😄 

Have you done something like this before? Do you know of a resource I can turn to? 

Thanks! I am looking forward to creating a PR for this, as soon as I sort out what steps are required

**Comment by mikker** [comment]
Hey! Nice. As with so much else, Rails has us pretty much covered. We just need to tell it where to look – see my PR #12.

I've added the necessary glue. I'll leave it to you to go through the code and see what we might want to provide translation points for. Ok?

**Comment by mftaff** [comment]
Cool! that is way simpler than I thought it would be.

Do you mind merging that pr? This way I can pull it down to my fork to add translations.

**Comment by mikker** [comment]
You can pull down the branch that I committed it to. But don’t bother – I’ve merged it as you asked. Thanks for taking a look!
