### ISSUE TITLE
Sidekiq integration 

### ISSUE THREAD

**Issue by Tioneb12** [mikker/passwordless#130]
Hi,

I get an error routind with sidekiq intégration :

```
require 'sidekiq/web'
require 'admin_constraint'

Rails.application.routes.draw do
  passwordless_for :users, at: '/', as: :auth
  
    scope 'admin', module: 'admin', as: 'admin' do
      mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
    end
end
```

All my emails form my webapp get an errro :

NoMethodError: undefined method `passwordless_with' for #<Class:0x00007fc9505bcce8>

How can I fix it ?

**Comment by mzrnsh** [comment]
Don't know if this helps but I posted how I made Sidekiq and Passwordless play along right here: https://github.com/mikker/passwordless/issues/125
