### ISSUE TITLE
Rails 7 redirection error due to allow_other_host option not being true

### ISSUE THREAD

**Issue by bcasci** [mikker/passwordless#140]
I'm working with a multi-tenant app, and there is a need move users between subdomains. The app running with Rails 7. There is a `redirect_to` call in the `passwordless` source that does not use the `allow_other_host` option, which throw an errors when using Rails 7 because that option is defaulted to `false`

My proposal, which I can do if the solution is agreed upon, is to allow the `passwordless` configuration `*_redirect_path` setting to take a `Proc`, in addition to a string. This way the host application could provide a bit more specificity about how a redirection should function.

What do you think? Is there a better solution?

**Comment by bcasci** [comment]
@mikker what do you think about this idea?

**Comment by mikker** [comment]
Sounds okay 👍 PR welcome
