### ISSUE TITLE
Bug: Release has outdated source for router_helpers.rb

### ISSUE THREAD

**Issue by dan003400** [mikker/passwordless#156]
After fetching and unpacking the gem, it is clear that the route_helpers file is out of date, causing there to be issues using the controller param.

This is in the latest release 0.12.0:

```
def passwordless_for(resource, at: nil, as: nil)
      mount_at = at || resource.to_s
      mount_as = as || resource.to_s
      mount(
        Passwordless::Engine,
        at: mount_at,
        as: mount_as,
        defaults: {authenticatable: resource.to_s.singularize}
      )

      Passwordless.mounted_as = mount_as
    end
```

**Comment by dan003400** [comment]
I have also noticed that Passwordless.configure is not available and the module Passwordless is very different unpacked compared to the source here.

**Comment by dan003400** [comment]
Unless I am not understanding something, it appears all the tagged releases are very outdated code, it feels like there is something very strange going on here.

Only way I can get anything to work is to point my Gemfile to the actual repo url.

**Comment by puffo** [comment]
I'm seeing the same problem. Pretty sure an update is needed to the release on RubyGems. 

I was attempting to use the routing helpers:
```
passwordless_for :uses, controller: 'sessions'
```
but it throws an error: `gems/passwordless-0.12.0/lib/passwordless/router_helpers.rb:19:in 'passwordless_for': unknown keyword: :controller (ArgumentError)`

**Comment by dan003400** [comment]
Yup, this is due to the ruby gems bundle being very outdated, I was able to correct the issue for now by pointing my gemfile directly to the repo for the time being.

**Comment by mikker** [comment]
Hey there. You're correct in your diagnose. Passwordless is in the middle of its biggest update yet and `master` has several breaking changes from the most recent released versions.

There's absolutely nothing wrong with the released versions though. But if you're building something new, master is probably the best choice right now. There'll be a few more changes before the next release though.

**Comment by dan003400** [comment]
Makes sense, only issue I see is that the current documentation is not for the latest release.

**Comment by mikker** [comment]
Added a note to the README.
