### ISSUE TITLE
app/views/passwordless/sessions/new.html.erb - label for does not match field ID

### ISSUE THREAD

**Issue by yshmarov** [mikker/passwordless#170]
this is the generated HTML for `app/views/passwordless/sessions/new.html.erb`:

<img width="916" alt="Screenshot 2023-10-15 at 15 43 06" src="https://github.com/mikker/passwordless/assets/13472945/8ad14212-7694-4b8b-96a8-38eaf9661e9b">

The `<label for=*` tag and the `<input id=>*` do not match.

This way, clicking on the lable will not focus into the input.

=> This is not very well generated HTML 🙃

**Comment by mikker** [comment]
Fixed, thank you!
