### ISSUE TITLE
Case sensitive?

### ISSUE THREAD

**Issue by stephenson** [mikker/passwordless#18]
It seems like passwordless is case sensitive Niklas@stephenson.dk is not niklas@stephenson.dk, this confuses users.

Can it be fixed in a way?

**Comment by mikker** [comment]
It's case-insensitive on lookup:
https://github.com/mikker/passwordless/blob/master/app/controllers/passwordless/sessions_controller.rb#L94

**Comment by mikker** [comment]
Or no – I guess it isn't.

**Comment by mikker** [comment]
Fixed in `v0.5.1`
