### ISSUE TITLE
Bug: default_url_options[:host] is required for mailer

### ISSUE THREAD

**Issue by arrowcircle** [mikker/passwordless#184]
Hey! I found a bug, when using sidekiq to send emails. To reproduce, uncomment this in passwordless initializer

```ruby
config.after_session_save = lambda do |session, request|
    Passwordless::Mailer.sign_in(session, session.token).deliver_later
  end
```

Set sidekiq as active_job adapter `config.active_job.queue_adapter = :sidekiq`

Then with working mailer, it will fail to deliver email saying about missing host.
This is fixed adding line to production.rb after config.action_mailer.default_url_options
```ruby
routes.default_url_options[:host] ||= "www.example.com"
```

**Comment by mikker** [comment]
Not a bug per se and also already mentioned in the docs. https://github.com/mikker/passwordless#urls-and-links

I agree that it could be more visible though

**Comment by arrowcircle** [comment]
Hey! Thanks for the answer.
I think I didn't communicated problem properly. Even with set action_mailer routes host it does not work without adding routes.default_url_options. So it works only if both mailer and routes options are set

```
config.action_mailer.default_url_options = {host: "www.example.com"}
routes.default_url_options[:host] ||= "www.example.com"
```

**Comment by mikker** [comment]
I see. What do you suggest? Should we make this more clear in the setup instructions?

**Comment by arrowcircle** [comment]
I think we could at least mention this in the readme, so if anyone else struggle with this problem will not spend time trying to understand what is going wrong.

**Comment by alexebird** [comment]
(Responding re: #186)

I think just updating the docs would be good enough.

**Comment by mikker** [comment]
I've updated the README to include your example config @arrowcircle. Thank you for reporting this and providing a fix.
https://github.com/mikker/passwordless/blob/master/README.md#urls-and-links

**Comment by dan003400** [comment]
How can this be the actual solution?

It makes no sense to supply `default_url_options host: 'www.example.com'` in the routes.rb file as this is specific to the environment, the example should also not suggest to `config.action_mailer.default_url_options = {host: "www.example.com"}` in the application.rb file as this would never be the case as development and production will always be different.

How should this properly be handled? I should add, we did not see this issue in projects using rails 7.1.1 only 7.1.2
