### ISSUE TITLE
specifying redirect url after login

### ISSUE THREAD

**Issue by noctivityinc** [mikker/passwordless#19]
How can we change the url of the magic link so we can send a logged in user to a different page then the root url?

**Comment by mikker** [comment]
Hi! This isn't configurable right now. Would love a pull request if you're up for adding it!

Here's where it happens: https://github.com/mikker/passwordless/blob/master/app/controllers/passwordless/sessions_controller.rb#L58
Options are specified in https://github.com/mikker/passwordless/blob/master/lib/passwordless.rb
