### ISSUE TITLE
current_user action controller

### ISSUE THREAD

**Issue by nasserfq** [mikker/passwordless#204]
Hello everyone! I've followed the instructions and placed 'current_user' action controller in application_controller.rb. The gem functions correctly, but the problem is that it invokes 'current_user' when the app initially starts running instead of the index action. Should I use filters in application_controller.rb or what? Note: I am still learning Rails and relying heavily on AI for solutions or guidance. Thank you!

**Comment by mikker** [comment]
Hi! Please provide relevant parts of the code you already have. Much easier to help you if we can see what you're trying 😊

**Comment by nasserfq** [comment]
![image](https://github.com/mikker/passwordless/assets/36525478/6652c7fa-a46a-4969-bb1f-85718050fc12)

I was wondering why current_user invoked in the initial app request even though it's not needed --> this's what I thought. But someone told me it's needed to be invoked to determine if a visitor logged in or not! Now I get the logic behind it! Finally, Thank you for building and providing this great gem ☺️

**Comment by mikker** [comment]
Glad you worked out your problem 😊
