### ISSUE TITLE
Allow customizing destination after sign in

### ISSUE THREAD

**Issue by mikker** [mikker/passwordless#21]
We would like to be able customize where users are sent upon successful authentication:

Happens here: https://github.com/mikker/passwordless/blob/master/app/controllers/passwordless/sessions_controller.rb#L58

Should be an option like the others in https://github.com/mikker/passwordless/blob/master/lib/passwordless.rb

(See #19)

**Comment by dankimio** [comment]
It would be nice to have an option to customize flash messages when redirecting the user back.

Could be an option in `save_passwordless_redirect_location` or elsewhere.

**Comment by mikker** [comment]
This was added in https://github.com/mikker/passwordless/pull/69
