### ISSUE TITLE
sign in via QR code 📸

### ISSUE THREAD

**Issue by yshmarov** [mikker/passwordless#210]
I think it could be a great additional feature to enable sign in via QR code using [rqrcode](https://github.com/whomwah/rqrcode).

I managed to add it to my app by adding this code to `app/views/passwordless/mailer/sign_in.html.erb`:

```
ruby
<% qrcode = RQRCode::QRCode.new(@magic_link) %>

<% svg = qrcode.as_svg(
  offset: 0,
  color: '000',
  shape_rendering: 'crispEdges',
  module_size: 11,
  viewbox: true, # to control width within div. if not true, width is controlled by module_size
  standalone: true) %>

<div style="width: 200px;">
  <%= raw svg %>
</div>
```

result:

<img width="1098" alt="Screenshot 2024-03-10 at 16 12 06" src="https://github.com/mikker/passwordless/assets/13472945/5e905236-9b66-42b5-98b6-869449e65369">

Although so far I did not find a nice way to display the QR code in plain-text email:

<img width="854" alt="Screenshot 2024-03-10 at 16 16 57" src="https://github.com/mikker/passwordless/assets/13472945/649ba6cd-c444-4e73-8bac-d679f58d6adb">

**Comment by mikker** [comment]
That's nice! I don't think it should go into the stock setup, adding a dependency and all.

I do however love having an example like this around. Let's add it to the docs or perhaps the wiki instead?

**Comment by yshmarov** [comment]
> That's nice! I don't think it should go into the stock setup, adding a dependency and all.
> 
> I do however love having an example like this around. Let's add it to the docs or perhaps the wiki instead?

[Added to wiki](https://github.com/mikker/passwordless/wiki/sign-in-via-QR-code-📸)

**Comment by mikker** [comment]
Wonderful! Thank you again @yshmarov 💙💛
