### ISSUE TITLE
Add `after_session_confirm` hook after session confirmation

### ISSUE THREAD

**Issue by onedanshow** [mikker/passwordless#213]
Just a suggestion to add a `after_session_confirm` similar to `after_session_save`. This would let folks mark accounts as "verified" or "has_verified_email" after session confirmation.

**Comment by mikker** [comment]
Good idea!

**Comment by onerinas** [comment]
This would be a great feature. I'm marking the "email_verified" field if current_user is present. This check is added in ApplicationController, which is not ideal as it checks on every single request.

I looked around the code to see if I can contribute in any way but not sure what would be the best way to add this. May be somewhere in `authenticate_and_sign_in`?

**Comment by wilburhimself** [comment]
I submitted a PR #237  that solves this issue and adds a configuration key to setup the hook like:

```ruby
Passwordless.configure do |config|
  config.after_session_confirm = ->(session) {
    user = session.authenticatable
    user.update(email_verified: true)
  }
end
```

@mikker @onerinas @onedanshow  @Ardnived

**Comment by mikker** [comment]
Responded in PR. Thank you for contributing @wilburhimself !
