### ISSUE TITLE
Don't isolate namespace

### ISSUE THREAD

**Issue by mikker** [mikker/passwordless#22]
Isolating namespace adds a bit of confusion around the routes. For a gem like ours this probably adds more trouble than benefit.

**Comment by nickisnoble** [comment]
Any movement here? Running into this currently – also just generally wondering if there's an example to completely customize routes ie `/login`. This gem is _very_ hard to google 😄

**Comment by mikker** [comment]
This is scheduled for 1.0 (#89) but there's no timeline for when that will be done.

The `passwordless_for` method is merely a helper for mounting the engine. See [router_helpers.rb](https://github.com/mikker/passwordless/blob/master/lib/passwordless/router_helpers.rb) to get a sense of how to customize routes further than with `as:` or `at:`.

**Comment by nickisnoble** [comment]
Ah, thank you!!
