### ISSUE TITLE
feature request: add ability to create custom layout for passwordless views

### ISSUE THREAD

**Issue by alec-c4** [mikker/passwordless#236]
Hey!
It would be nice if there will be ability to add custom layout for passwordless views.

**Comment by mikker** [comment]
There's a few ways to do this.

I think, if you just make a `app/views/layouts/passwordless.html.erb` it will be used?

Otherwise, consider making a custom controller:

```ruby
class SessionsController < Passwordless::SessionsController
end
```

+ `app/views/layouts/sessions.html.erb`

```ruby
passwordless_for :users, controller: "sessions"
```

**Comment by alec-c4** [comment]
Hey!

> I think, if you just make a app/views/layouts/passwordless.html.erb it will be used?

Unfortunately, it doesn't work :(

**Comment by mikker** [comment]
Good to know!
