### ISSUE TITLE
JWT Support

### ISSUE THREAD

**Issue by ro-savage** [mikker/passwordless#36]
Any plans to support JSON Web Tokens as well as sessions?

**Comment by mikker** [comment]
Nope, but PRs are welcome 😊

**Comment by stas** [comment]
Not entirely related to this project, but wanted to mention a little project that I started to help build passwordless APIs: https://github.com/stas/otp-jwt

Also thanks @mikker for the inspiration. :bowing_man:

**Comment by mikker** [comment]
> Main goals:
> * No magic please

I feel attacked 😉 

But seriously: Great to have more choices! I'll link it in the README.

**Comment by avinoth** [comment]
How exactly would we integrate JWT with this? This auto-signs the user using sessions, instead generate a JWT on link click? I think i'm missing something here.. help @mikker
