### ISSUE TITLE
Allow user to type in/copy paste token in same window after requesting?

### ISSUE THREAD

**Issue by mikker** [mikker/passwordless#47]
This is something I've seen other implementations do. This helps if for example you are trying to sign in using your laptop but check your mail on your phone.

Using a `TokenGenerator` that generates passphrases of English words remembering and typing is easy enough.

**Comment by avinoth** [comment]
This would be neat. We could put up an input box in the "Token sent, check your email page" and users can either directly authenticate with a token, or enter the passphrase (both will be on the email we send).

Couple of questions though,

* How would we allow the customization of the page? do you have some ideas?
* Should we just replace the existing token mechanism and go ahead with aforementioned way or allow both to co-exist and let the app developer turn on `Enter OTP` if needed? the former will be breaking change and the latter will be little bit more work lol.

let me know

**Comment by mikker** [comment]
Included in upcoming 1.0. See #159
