### ISSUE TITLE
only allow users with emails matching a certain criteria?

### ISSUE THREAD

**Issue by maia** [mikker/passwordless#54]
I would like to restrict sending emails with sign-in-tokens to users with an email of a specific domain. How would I need to configure passwordless to return an error message if the email entered at sign_in does not match a specific criteria?

I assumed I would need to create a custom `User#fetch_resource_for_passwordless` method, but even when returning nil instead of a created user object I'm redirected to sign_in with the message "If we found you in the system, we've sent you an email." – is there a way to either redirect to another page or return a different flash message when creation of a user fails?

Thanks a lot!

(As additional information: the referenced app did not include any User model/controller, so there is no specific code other than mentioned in this README.md, this app basically only had a root page with a single controller, only protected with a simple http_basic_authenticate_with as it wasn't ready to be available to anyone except myself so far, but now I'd like to make it available to my colleagues at work)

**Comment by mikker** [comment]
Hi there! You're in charge of providing the method of creating users. If you only allow users with email addresses on that domain to sign up then you don't need to restrict the login mechanism. Right?

**Comment by maia** [comment]
Thanks for your reply. My issue is that passwordless ignores a custom `UserController#create` as suggested at https://github.com/mikker/passwordless#registering-new-users which could check the email and only sign_in and redirect accordingly – the form at users.sign_in_path will POST to "/users/sign_in", and the engine routes will forward that to Passwordless::SessionsController#create. So with the suggested setup at README.md it seems there is nothing that would ever call UserController#create. 

Should I not use `passwordless_for :users` in my routes, instead only use `resources :users` and additional custom routes to call the Passwordless::SessionsController actions after processing the email in `UserController#create`?

What important part of the puzzle am I missing here? Thanks a lot!

**Comment by mikker** [comment]
Passwordless only handles authentication flows. There is no `UsersController` unless you make one yourself. I can see how the README could be a bit vague in describing this.

In your case, as I understand it, you should create a `UsersController` yourself, have both `passwordless_for :users` _and_ `resources :users` in your routes.

**Comment by mikker** [comment]
To be clearer: Passwordless will not put any `User`s in your database. You have to provide that part yourself. Passwordless will only put `Passwordless::Session`s in your database to sign in users (or any other model you tell it to).

**Comment by maia** [comment]
Thanks, I altered the routes to keep users and sessions clearly separated, it did confuse me that sessions are created at a path that had "users" in its name. But still I didn't get it to work, and I think the issue is that `Passwordless::SessionsController#create` always calls `Passwordless.after_session_save.call`, even if the session did not save.

The following will unfortunately always render /sign_in with the note "If we found you in the system, we've sent you an email." after submitting the form, even if no user is created, and that's what I'm trying to change:
```ruby
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  passwordless_with :email

  def self.fetch_resource_for_passwordless(email)
    email.ends_with?('customdomain.com') ? find_or_create_by!(email: email) : nil
  end
end
```
What I'd want is to display a different message if a user was not created.

Here's the rest of my setup:
```ruby
# routes.rb
Rails.application.routes.draw do
  passwordless_for :users, at: '/sessions', as: :sessions
  resources :users
  # …
end

# application_controller.rb
class ApplicationController < ActionController::Base
  include Passwordless::ControllerHelpers
  helper_method :current_user

  private
    def current_user
      @current_user ||= authenticate_by_cookie(User)
    end

    def require_user!
      return if current_user
      save_passwordless_redirect_location!(User)
      redirect_to sessions.sign_in_path, flash: {error: 'Please enter your email to have a login link sent to your inbox'}
    end
end

# user_controller.rb
class UserController < ApplicationController
end

# schema.rb
ActiveRecord::Schema.define(version: 2019_05_13_211801) do
  # …
  create_table "passwordless_sessions", force: :cascade do |t|
    t.string "authenticatable_type"
    t.bigint "authenticatable_id"
    t.datetime "timeout_at", null: false
    t.datetime "expires_at", null: false
    t.text "user_agent", null: false
    t.string "remote_addr", null: false
    t.string "token", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["authenticatable_type", "authenticatable_id"], name: "authenticatable"
  end

  create_table "users", force: :cascade do |t|
    t.string "email"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
end
```
And in case it's of any relevance: my goal isn't to create users with much information, all I want is to restrict access to the app to people with emails of a certain domain. I just added the users table as it seems to be necessary for passwordless. I could add custom views and controller methods for User, but then I assume the logic would be to initially ask people to enter their email address in UserController#new, then create them in the db when the domain is correct, and then forward them to sign_in to ask them to re-enter their email address? 

I'd prefer to have one view where people enter their email, and either are sent an email with a login token, or are shown an error message telling them that access is restricted to email addresses of a certain domain. How would this be possible?

Thanks!

**Comment by maia** [comment]
I'm one step further, I guess I need to override the view by creating `app/views/passwordless/sessions/create.html.slim` and customize the output depending on if the session was saved or not. 

Now the remaining question is: how do I access the session instance variable defined in [controllers/passwordless/sessions_controller.rb](https://github.com/mikker/passwordless/blob/a6aeea188e06912b9cbe883296a739382aa0f0e7/app/controllers/passwordless/sessions_controller.rb#L25-L37) in my view to then either display a success message (`I18n.t('passwordless.sessions.create.email_sent_if_record_found')`) or an error message, in case the session object wasn't saved? 

If passwordless would use something like `render :create, locals: { session: session }` instead of a plain `render`, the view could access it (although I could imagine that `session` might be a problematic variable name). But I assume there's a smarter way, e.g. by passing different locals to the view depending on if `session.save` failed or not.

**Comment by mikker** [comment]
I’m not sure we’re talking about the same thing here. If you only want users with a certain domain, just don’t create any without it.

You want to create missing users when they try to sign in? Use the SessionHelpers’ sign_in in your custom UsersController.

**Comment by maia** [comment]
I want the root page of my app present a form for an email address. If people enter an email address of a certain domain, they are sent a login link (and by clicking it, they are signed in and stay so for a few months). If they enter any other email, they are shown an error message that access is denied. That's all. I don't care if email addresses are permanently saved in the db users table or not, and the frontend will never display any user related information (other than maybe a sign-out link, but nothing more).

Unfortunately I don't understand how this would be possible – could you be more specific in where you'd suggest to do so? What in the code above would need to be deleted or added? 

When using…
```ruby
def self.fetch_resource_for_passwordless(email)
  email.ends_with?('customdomain.com') ? User.find_or_create_by!(email: email) : nil
end
```
…I cannot find a way to prompt an access restricted message if user creation failed, as the rendered view does not contain a local variable indicating if the session was saved or not (because a session will not be saved when missing information about an associated user). 

I hope it's clearer now what the goal is? Thanks!

**Comment by mikker** [comment]
Forget everything you have posted above, then:

```ruby
resources :users, only: [:create]
root to: "users#new"
```

```ruby
class User < ApplicationRecord
  validate :email_domain
  
  private

  def email_domain
    return true if email&.ends_with?('@google.com')
    errors.add(:email, 'does not belong to Google')
  end
end
```

```ruby
class UsersController < ApplicationController
  include Passwordless::ControllerHelpers

  def new
    # render form with input name=user[email]
  end

  def create
    user = User.new(user_params)
    
    if user.save
      sign_in! user
      redirect_to somewhere_authenticated_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end
end
```

Important to note: The only two things that have to do with Passwordless are `include Passwordless::ControllerHelpers` and `sign_in! user`.

Have not tested the above code.

**Comment by maia** [comment]
Much appreciated, thank you, I will test this later today and report if everything worked. I'm unsure where the magic of sending the token (and therefor authentication of the entered email address) will happen in your suggested code, but I will figure it out once I have time.

**Comment by mikker** [comment]
I updated the comment.

**Comment by maia** [comment]
Mikker, thanks. And in case anyone else is interested in the future: mikkers suggestion worked, the only necessary addition is `passwordless_with :email` in user class, as otherwise `build_passwordless_session(user)` returns `Could not find the inverse association for authenticatable (:passwordless_sessions in User)`.

**Comment by mikker** [comment]
Yesss, forgot that one 😊 should probably raise a more helpful error instead. Thanks for using Passwordless!

**Comment by maia** [comment]
Thanks for writing passwordless! :)
