### ISSUE TITLE
Support for model that is not named "User"

### ISSUE THREAD

**Issue by alexdesi** [mikker/passwordless#57]
I did not find the answer of this on the docs (I might have overlooked it).
I am trying to use `passwordless`,  I do not have a model name `User`, the model used in the authentication is named `Teacher`.

So in the routes.rb, I got:
`passwordless_for :teachers`

but when I access to `/teachers/sign_in/my-token` I get:

```
NameError in Passwordless::SessionsController#show
uninitialized constant Passwordless::SessionsController::User
```
Is there a way to use a model NOT named `User`? if so what I am missing?

Note that the view `/teachers/sign_in` works as expected.

Thanks!

**Comment by mikker** [comment]
I think a rogue `User` snuck in here https://github.com/mikker/passwordless/blob/28303ef0aeb8bdd72dd081ddf5d18577da8ed2ec/app/controllers/passwordless/sessions_controller.rb#L48

Thanks for finding it! I'll take a look.

**Comment by mikker** [comment]
Just pushed 0.8.1 with a fix for this. Thanks for reporting!
