### ISSUE TITLE
Add routes examples to README

### ISSUE THREAD

**Issue by dankimio** [mikker/passwordless#60]
It was a bit unclear how routes work in passwordless. I added `passwordless_for :companies` and expected something like `company_sign_in_url`.

`$ rails routes` command shows the following: `sign_in GET /sign_in(.:format) passwordless/sessions#new`. Only after a few hours of experimenting and reading through the source I realized I had to write `companies.sign_in_path`. Would be nice if we added some examples on generated routes.

**Comment by mikker** [comment]
You are right that this is confusing. Confused me too! It's how `isolate_namespace` works in Rails Engines.

I've been wanting to disable that so we can get ordinary-looking urls. The issue is this one #22.

A PR with a section in the README would be much appreciated! ❤️

**Comment by mikker** [comment]
See also this comment: https://github.com/mikker/passwordless/issues/30#issuecomment-435142143
