### ISSUE TITLE
Sponsoring doesn't work

### ISSUE THREAD

**Issue by dankimio** [mikker/passwordless#62]
I get the following error:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/6442492/64478233-6a991a00-d19d-11e9-9dea-1e66ac35921d.png">

**Comment by mikker** [comment]
Hi @dankimio! I appreciate the intention! I'm not in the Sponsor programme yet but was curious and added the file. I've updated it to be a link to my portfolio-ish site instead.

If I get accepted to the programme, I'll update this issue.
