### ISSUE TITLE
Instant sign up

### ISSUE THREAD

**Issue by dankimio** [mikker/passwordless#63]
First of all, thanks for the gem, great work!

Some apps do not require separate registration and combine sign in and sign up forms. If there's no user with such email, the app creates a user with that email and sends a confirmation link.

How can this flow be implemented with passwordless?

**Comment by mikker** [comment]
Thank you 😊 

You could do that by stitching together half of the [Registering users example](https://github.com/mikker/passwordless#registering-new-users) and the contents of [`create` in `SessionsController`](https://github.com/mikker/passwordless/blob/master/app/controllers/passwordless/sessions_controller.rb#L22).

```ruby
if (user = User.find_by(email: params[:email])
  # send email
else
  # create user, send email/sign in
end
```

I won't write an example for you but do update this if you make something work!

**Comment by dankimio** [comment]
What would be the correct procedure for overriding `SessionsController`?

**Comment by dankimio** [comment]
Okay, so I implemented `fetch_resource_for_passwordless` with `find_or_create_by(email: email)` in my class and it basically works as instant sign-up.
