### ISSUE TITLE
View generators

### ISSUE THREAD

**Issue by dankimio** [mikker/passwordless#64]
Custom views and controllers could be generated the same way they are generated in Rails or Devise via `$ rails g devise:views`. I would gladly submit a PR for that.

**Comment by mikker** [comment]
Thanks! Sure, I'd consider adding something like that. I'd want it to be as little code as possible though. Managing _both_ the bundled views _and_ the generated ones are going to be a hassle. As the bundled views already work and can be copied directly – could we make the generator just do so? Copy the bundled ones as the README also suggests?
