### ISSUE TITLE
Test helpers

### ISSUE THREAD

**Issue by dankimio** [mikker/passwordless#71]
Something like Devise's `sign_in @user` helper.

See also #29.

**Comment by mikker** [comment]
Hi @dankimio!

I think this could be a nice addition. What kinds of tests would you expect to use this in? `request`, `controller`, `system`?

**Comment by dankimio** [comment]
Hello!

I think both controller (integration) and system would be nice to have for starters, and would cover most cases.

Devise has [IntegrationHelpers](https://github.com/plataformatec/devise/blob/master/lib/devise/test/integration_helpers.rb).

**Comment by Uysim** [comment]
Since there is no help in this yet i do like this
```ruby
  def passwordless_sign_in(resource)
    session = Passwordless::Session.create!(
      authenticatable: resource,
      user_agent: 'Command Line',
      remote_addr: 'unknown'
    )

    visit Passwordless::Engine.routes.url_helpers.token_sign_in_path(session.token)
  end
```

**Comment by crispinheneise** [comment]
How would you do this in controller tests?

**Comment by mikker** [comment]
You could just mock it. If you're using RSpec, something like

```ruby
def sign_in(user)
  allow(controller).to receive(:current_user) { user }
end
```

**Comment by scomma** [comment]
@crispinheneise you could use @Uysim's code and substitute `get` for `visit`

**Comment by crispinheneise** [comment]
@scomma yes, I did use @Uysim's suggestion. 

Here's a module that can be included in `test_helper.rb` or dropped in `test/support/`

```rb
module PasswordlessSupport
  module TestCase
    def passwordless_sign_out
      delete Passwordless::Engine.routes.url_helpers.sign_out_path
    end

    def passwordless_sign_in(resource)
      session = Passwordless::Session.create!(authenticatable: resource, user_agent: 'TestUnit', remote_addr: 'unknown')
      get Passwordless::Engine.routes.url_helpers.token_sign_in_path(session.token)
    end
  end

  module SystemTestCase
    def passwordless_sign_in(resource)
      session = Passwordless::Session.create!(authenticatable: resource, user_agent: 'TestUnit', remote_addr: 'unknown')
      visit Passwordless::Engine.routes.url_helpers.token_sign_in_path(session.token)
    end
  end
end

class ActiveSupport::TestCase
  include ::PasswordlessSupport::TestCase
end
class ActionDispatch::SystemTestCase
  include ::PasswordlessSupport::SystemTestCase
end
```

Any recommendations on DRY-ing up this module?

**Comment by mikker** [comment]
Looks good, @crispinheneise! I don't see a reason to DRY anything up. Very short and succinct 👍

**Comment by fa11enangel** [comment]
> @scomma yes, I did use @Uysim's suggestion.
> 
> Here's a module that can be included in `test_helper.rb` or dropped in `test/support/`
> 
> ```ruby
> module PasswordlessSupport
>  ...
> end
> ```
> 
> Any recommendations on DRY-ing up this module?

I've tried to use it. It works, but there is `follow_redirect!` missing for get and delete. If you'll sign_in or sign_out and try to access another url afterwards, the url will be broken, as the redirect after login was not finished yet.

```ruby
module PasswordlessSupport
  module TestCase
    def passwordless_sign_out
      delete Passwordless::Engine.routes.url_helpers.sign_out_path
      follow_redirect!
    end

    def passwordless_sign_in(resource)
      session = Passwordless::Session.create!(authenticatable: resource, user_agent: 'TestUnit', remote_addr: 'unknown')
      get Passwordless::Engine.routes.url_helpers.token_sign_in_path(session.token)
      follow_redirect!
    end
  end

  module SystemTestCase
    def passwordless_sign_in(resource)
      session = Passwordless::Session.create!(authenticatable: resource, user_agent: 'TestUnit', remote_addr: 'unknown')
      visit Passwordless::Engine.routes.url_helpers.token_sign_in_path(session.token)
    end
  end
end

class ActiveSupport::TestCase
  include ::PasswordlessSupport::TestCase
end
class ActionDispatch::SystemTestCase
  include ::PasswordlessSupport::SystemTestCase
end
```
