### ISSUE TITLE
initializer Passwordless.token_generator default value error

### ISSUE THREAD

**Issue by no1-knows** [mikker/passwordless#74]
I'm newbie so I cant understand whats problem.

I just follow [https://github.com/mikker/passwordless#configuration](https://github.com/mikker/passwordless#configuration) and `uninitialized constant UrlSafeBase64Generator (NameError)` error occurred when server start.

FYI

**Comment by mikker** [comment]
It should be `Passwordless::UrlSafeBase64Generator.new`, sorry. There's an error in the docs.

**Comment by mikker** [comment]
Fixed in https://github.com/mikker/passwordless/commit/bb0adfcbd0744b05601d879bcb5aa0311c8225cc
