### ISSUE TITLE
There is should be some global expose on create render

### ISSUE THREAD

**Issue by Uysim** [mikker/passwordless#76]
What I want is 

```ruby
- If @resource.present
   = message
- else
   = other_message
```

By override view but is not possible

**Comment by mikker** [comment]
I agree.

At first this was ambiguous on purpose for security reasons but as most apps (I guess) also have some sort of signup form that requires a unique email address, it doesn't provide any security benefits here anyway.

I like your approach of making the resource available and let the app developer choose whether they want to show that one was found only by overriding the view.

PRs welcome 😊

**Comment by Uysim** [comment]
@mikker I submit pull request #77
