### ISSUE TITLE
Initializing parent_mailer

### ISSUE THREAD

**Issue by djolereject** [mikker/passwordless#87]
I simply copied your example and got an error. This line in initalizer:

`Passwordless.parent_mailer = "ActionMailer::Base"`

is producing this error:
```
 undefined method `parent_mailer=' for Passwordless:Module (NoMethodError)
Did you mean?  parent_name
```

Any idea what could be wrong there?

**Comment by xdmx** [comment]
@djolereject it's not been released yet, to use it in the meantime you can fetch the current code from the repository like: `gem "passwordless", github: "mikker/passwordless"`

@mikker it'd be nice to have a new version for this :smile:

**Comment by djolereject** [comment]
Thank you!
